# Generated by Django 2.2.3 on 2019-07-19 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuisine',
            old_name='cuisine',
            new_name='name',
        ),
    ]
