# Generated by Django 2.2.3 on 2019-07-24 03:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20190724_0313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedrecipe',
            unique_together={('user', 'recipe_id')},
        ),
        migrations.RemoveField(
            model_name='savedrecipe',
            name='saved',
        ),
    ]
