# Generated by Django 2.2.3 on 2019-07-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190724_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='recipe_link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='recipe_title',
            field=models.CharField(default=2, max_length=512),
            preserve_default=False,
        ),
    ]
