# Generated by Django 2.2.3 on 2019-07-27 13:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedrecipe',
            unique_together={('user', 'recipe_id')},
        ),
    ]
