# Generated by Django 2.2.3 on 2019-07-24 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_savedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='saved',
            field=models.ManyToManyField(related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe_id',
            field=models.IntegerField(),
        ),
    ]
