# Generated by Django 2.2.3 on 2019-07-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190724_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='title',
            field=models.CharField(default='placeholder title', max_length=512),
            preserve_default=False,
        ),
    ]
