# Generated by Django 2.2.3 on 2019-07-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190726_0557'),
        ('core', '0006_savedrecipe_title'),
    ]

    operations = [
    ]
