# Generated by Django 2.2.3 on 2019-07-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20190727_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedrecipe',
            name='title',
        ),
    ]
